Repository MLforALL-app/MLforALL, pull requests merged in 2020-06, with the labels that each got.

#39 Reogranize create project
  frontend/src/App.js
  frontend/src/components/projects/newProject/buildproject.js
  frontend/src/components/projects/newProject/editpage/editCSV.js
  frontend/src/components/projects/newProject/editpage/modeloutput.js
  frontend/src/components/projects/newProject/editpage/modelselect.js
  frontend/src/components/projects/newProject/editpage/nanhandler.js
  frontend/src/components/projects/newProject/editpage/projectstatus.js
  frontend/src/components/projects/newProject/editproject.js
  frontend/src/components/projects/newProject/newprojectpage.js
  frontend/src/components/projects/newProject/uploadcsv.js
  frontend/src/components/projects/projectdetails/main.css
  frontend/src/store/actions/projectActions.js
  frontend/src/store/reducers/projectReducer.js
Labels: Redux

#45 "added descriptions"
  frontend/src/components/projects/newProject/editpage/modelcheck.js
  frontend/src/components/projects/projectdetails/slide/generateSliders.js
Labels: Styles, UI/UX

#49 Banner
  README.md
  frontend/src/pictures/backgrounds/banner.jpeg
  frontend/src/pictures/scripts/works.png
  frontend/src/pictures/scripts/wrongfolder.png
  frontend/src/pictures/scripts/wrongrepo.png
  scripts/README.md
Labels: Meta, Styles

#52 Monday meeting fixes
  README.md
  api/src/local_stats/load_and_predict.py
  api/src/variables.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/info/joeLand.js
  scripts/README.md
  scripts/mfa.sh
Labels: Firebase, Meta

#58 replaced waiting for csv to circle
  frontend/src/components/projects/newProject/editproject.js
Labels: Styles

#56 fix firestore, remove cloud fn
  api/src/app.py
  api/src/firebase.py
  frontend/functions/index.js
  frontend/public/index.html
  frontend/src/components/education/makeToolBar.js
  frontend/src/components/projects/newProject/editpage/nanhandler.js
  frontend/src/components/projects/newProject/editproject.js
  scripts/mfa.sh
Labels: Classify API, Firebase, bug
