Repository MLforALL-app/MLforALL, pull requests merged in 2020-07, with the labels that each got.

#66 Loading
  .gitignore
  api/src/app.py
  api/src/data.py
  api/src/firebase.py
  api/src/model.py
  frontend/public/index.html
  frontend/src/components/projects/newProject/editproject.js
  frontend/src/components/projects/projectdetails/cards/csvCard.js
  frontend/src/components/projects/projectdetails/projectdetails.js
  frontend/src/components/projects/projectdetails/slide/generateSliders.js
  frontend/src/components/projects/projectdetails/slide/predictslide.js
  frontend/src/components/projects/projectdetails/slide/resultCard.js
  frontend/src/store/actions/projectActions.js
  frontend/src/store/reducers/projectReducer.js
Labels: Firebase, Redux, bug

#68 Catch bad input
  frontend/src/components/projects/newProject/bigPapa.js
  frontend/src/components/projects/newProject/editpage/editCSV.js
  frontend/src/components/projects/newProject/editpage/modeloutput.js
  frontend/src/components/projects/newProject/editpage/modelselect.js
  frontend/src/components/projects/newProject/editproject.js
  frontend/src/store/actions/projectActions.js
  frontend/src/store/reducers/projectReducer.js
Labels: Redux, UI/UX, bug

#69 Aboutpage
  frontend/src/App.js
  frontend/src/components/auth/Signup.js
  frontend/src/components/info/about.js
  frontend/src/components/info/landing.js
  frontend/src/components/info/mobile.js
  frontend/src/components/layouts/Singedinlinks.js
  frontend/src/components/layouts/Singedoutlinks.js
  frontend/src/components/projects/projectdetails/slide/resultCard.js
  frontend/src/pictures/headshots/davis.jpg
  frontend/src/pictures/headshots/megha.jpg
  frontend/src/pictures/headshots/rong.jpg
  frontend/src/styling/landing.css
  frontend/src/styling/projectdetails.css
Labels: Styles, UI/UX

#70 Landing features
  frontend/src/components/info/landing.js
  frontend/src/pictures/landing/LP1.svg
  frontend/src/pictures/landing/LP2.svg
  frontend/src/styling/features.css
Labels: Styles

#73 Fix for Sliders + Database for Testing / Prod
  .gitignore
  api/src/app.py
  api/src/data.py
  api/src/model.py
  frontend/functions/index.js
  frontend/src/components/dashboard/userProfile.js
  frontend/src/components/projects/newProject/editproject.js
  frontend/src/components/projects/projectList/projectlist.js
  frontend/src/components/projects/projectdetails/projectdetails.js
  frontend/src/components/projects/projectdetails/slide/generateSliders.js
  frontend/src/components/projects/projectdetails/slide/predictslide.js
  frontend/src/config/collection.js
  frontend/src/store/actions/projectActions.js
  frontend/src/store/reducers/projectReducer.js
Labels: Firebase

#74 added project comfirm message
  frontend/src/components/projects/newProject/editpage/comfirmbuild.js
  frontend/src/components/projects/newProject/editproject.js
Labels: UI/UX

#75 Create project tweaks
  frontend/src/components/projects/newProject/editpage/comfirmbuild.js
  frontend/src/components/projects/newProject/editpage/editCSV.js
  frontend/src/components/projects/newProject/editpage/modeloutput.js
  frontend/src/components/projects/newProject/editpage/modelselect.js
  frontend/src/components/projects/newProject/editproject.js
  frontend/src/store/reducers/projectReducer.js
Labels: Meta

#76 Minor fixes
  README.md
  api/src/data.py
  api/src/local_stats/build_and_pickle.py
  api/src/local_stats/stat_util.py
  frontend/public/banner.jpeg
  frontend/public/favicon.png
  frontend/public/index.html
  frontend/public/squarelogo.jpg
  frontend/src/components/education/docs/additionalResourcesDocs.js
  frontend/src/components/education/docs/decisionTreeDocs.js
  frontend/src/components/education/docs/fileFormatter.js
  frontend/src/components/education/docs/gaussianNaiveBayesDocs.js
  frontend/src/components/education/docs/introductionDocs.js
  frontend/src/components/education/docs/kNearestNeighborsDocs.js
  frontend/src/components/education/docs/linearDiscriminantAnalysisDocs.js
  frontend/src/components/education/docs/logisticRegressionDocs.js
  frontend/src/components/education/docs/supportVectorMachineDocs.js
  frontend/src/components/education/mainDoc.js
  frontend/src/components/education/makeToolBar.js
  frontend/src/components/layouts/helpbox.js
  frontend/src/components/projects/newProject/editpage/editCSV.js
  frontend/src/components/projects/newProject/editpage/insights.js
  frontend/src/components/projects/newProject/editpage/modelcheck.js
  frontend/src/components/projects/newProject/editpage/modelselect.js
  frontend/src/components/projects/newProject/editpage/projectstatus.js
  frontend/src/components/projects/newProject/editproject.js
  frontend/src/components/projects/projectdetails/slide/generateSliders.js
  frontend/src/config/collection.js
  frontend/src/pictures/backgrounds/squarelogo.jpg
  frontend/src/store/actions/nameMapper.js
  frontend/src/styling/help.css
  frontend/src/styling/landing.css
  frontend/src/styling/projectdetails.css
Labels: Meta, Styles

#78 Aboutpage
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/auth/Signup.js
  frontend/src/components/info/about.js
  frontend/src/components/info/landing.js
  frontend/src/components/info/mobile.js
  frontend/src/components/layouts/Singedinlinks.js
  frontend/src/components/layouts/Singedoutlinks.js
  frontend/src/components/projects/projectdetails/slide/resultCard.js
  frontend/src/pictures/about/ausvg1.svg
  frontend/src/pictures/about/ausvg3.svg
  frontend/src/pictures/about/ausvg7.svg
  frontend/src/pictures/headshots/davis.jpg
  frontend/src/pictures/headshots/megha.jpg
  frontend/src/pictures/headshots/rong.jpg
  frontend/src/pictures/landing/LP1.svg
  frontend/src/pictures/landing/LP2.svg
  frontend/src/styling/about.css
  frontend/src/styling/cards.css
  frontend/src/styling/features.css
  frontend/src/styling/landing.css
  frontend/src/styling/projectdetails.css
Labels: Styles

#80 caught failing project creation, styling
  frontend/src/components/projects/newProject/editpage/comfirmbuild.js
  frontend/src/components/projects/newProject/editpage/nanhandler.js
  frontend/src/components/projects/newProject/editproject.js
  frontend/src/store/reducers/projectReducer.js
  frontend/src/styling/createproject.css
Labels: Styles, UI/UX, bug

#83 Help page
  api/src/data.py
  frontend/src/components/education/docs/decisionTreeDocs.js
  frontend/src/components/education/docs/gaussianNaiveBayesDocs.js
  frontend/src/components/education/docs/linearDiscriminantAnalysisDocs.js
  frontend/src/components/education/docs/supportVectorMachineDocs.js
Labels: enhancement

#89 Minor fixes
  README.md
  frontend/public/banner.jpeg
  frontend/public/banner.png
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/info/about.js
  frontend/src/components/info/landing.js
  frontend/src/components/layouts/Singedoutlinks.js
  frontend/src/components/projects/newProject/editproject.js
Labels: Styles, UI/UX, bug

#94 implemented error handling for failing project builds
  api/src/app.py
Labels: Classify API, bug
